export const ADD_TABLE = 'ADD_TABLE';
export const DELETE_TABLE = 'DELETE_TABLE';
export const UPDATE_TABLE_NAME = 'UPDATE_TABLE_NAME';

export const ADD_FIELD = 'ADD_FIELD';
export const DELETE_FIELD = 'DELETE_FIELD';
export const UPDATE_FIELD_NAME = 'UPDATE_FIELD_NAME';
export const UPDATE_FIELD_TYPE = 'UPDATE_FIELD_TYPE';

export const UPDATE_SCHEMA_OUTPUT = 'UPDATE_SCHEMA_OUTPUT';
